# -- Main Menu --
# Displayed in the header at the top of every page.

[[main]]
  name = "Vocation"
  pageRef = "vocation"
  weight = 10

[[main]]
  name = "Reflections"
  pageRef = "reflections"
  weight = 20

[[main]]
  name = "Wanderings"
  pageRef = "wanderings"
  weight = 30
