# -- Main Menu --
# Displayed in the header at the top of every page.

[[main]]
  name = "Career"
  pageRef = "vocation"
  weight = 10

[[main]]
  name = "Writings"
  pageRef = "reflections"
  weight = 20

[[main]]
  name = "Life"
  pageRef = "wanderings"
  weight = 30
